CREATE TABLE `authen_service_consumer` (
  `ID` varchar(32) NOT NULL,
  `CONSUMER_NAME` varchar(40) NOT NULL,
  `SECRT_KEY` varchar(128) NOT NULL,
  `CREATED_BY` varchar(32) NOT NULL,
  `UPDATED_BY` varchar(32) NOT NULL DEFAULT 'NEVER_CHANGE',
  `CREATED_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_SID` varchar(32) NOT NULL,
  `UPDATED_SID` varchar(32) NOT NULL DEFAULT 'NEVER_CHANGE',
  `REMARK` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `AK_UNIQUE_CONSUMER_NAME` (`CONSUMER_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;